# Generated by Django 3.2.6 on 2021-08-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_Preguntas', models.CharField(max_length=255)),
                ('fecha_publicacion', models.DateTimeField(verbose_name='Fecha de publicacion')),
            ],
            options={
                'db_table': 'preguntas',
            },
        ),
    ]
