# Generated by Django 3.2.6 on 2021-09-05 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_auto_20210905_1516'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quizusuario',
            table=None,
        ),
    ]
