# Generated by Django 3.2.6 on 2021-08-30 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcion',
            name='pregunta',
        ),
        migrations.AddField(
            model_name='opcion',
            name='correcta',
            field=models.BooleanField(default=False, verbose_name='es esta la pregunta correcta?'),
        ),
        migrations.AddField(
            model_name='opcion',
            name='cuestion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='administrador.pregunta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opcion',
            name='opcion_text',
            field=models.TextField(verbose_name='Texto de la respuesta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='pregunta_text',
            field=models.TextField(verbose_name='Texto de la pregunta'),
        ),
    ]
