# Generated by Django 3.2.6 on 2021-09-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apodo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='direccion',
        ),
    ]
